theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#689D6A"
idle_fg = "#D5C4A1"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
[block.theme_overrides]
idle_bg = "#B16286"
idle_fg = "#D5C4A1"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#458588"
idle_fg = "#D5C4A1"

[[block]]
block = "load"
interval = 1
format = "{1m}"
[block.theme_overrides]
idle_bg = "#D79921"
idle_fg = "#D5C4A1"

[[block]]
block = "sound"
[block.theme_overrides]
idle_bg = "#98971A"
idle_fg = "#D5C4A1"

[[block]]
block = "time"
interval = 5
format = "%d.%m.%y %I:%M%P"
[block.theme_overrides]
idle_bg = "#CC241D"
idle_fg = "#D5C4A1"
